apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-service
  labels:
    app: alarm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-service
  template:
    metadata:
      labels:
        app: alarm-service
    spec:
      containers:
      - name: alarm-service
        image: plc-alarm-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4060
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-service
spec:
  selector:
    app: alarm-service
  ports:
    - protocol: TCP
      port: 4060
      targetPort: 4060
