apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-service
  labels:
    app: sensor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-service
  template:
    metadata:
      labels:
        app: sensor-service
    spec:
      containers:
      - name: sensor-service
        image: plc-sensor-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4020
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-service
spec:
  selector:
    app: sensor-service
  ports:
    - protocol: TCP
      port: 4020
      targetPort: 4020
